name: tests

on: [push]

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH

      - run: cargo test
